language: java
install: ant

notifications:
  email:
    recipients:
	- nico.garofalo98@gmail.com
	- constanza.frutos.ramos@gmail.com
	- enzoponf3@gmail.com
	- sebapenna19@gmail.com
    on_success: always # default: change
