language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
     - nico.garofalo98@gmail.com
     - constanza.frutos.ramos@gmail.com
     - enzoponf3@gmail.com
     - sebapenna19@gmail.com
    on_failure: always
    on_success: always

